### PR TITLE
Fix Visual Studio 2022 build

### PR DESCRIPTION
**Pull request by xoascf**
- Fixes Visual Studio 2022 build
- Updates HIDAPI to 0.13.1

### CODE REVIEW

**Comment by RyzenDew** [comment]
Post that it compiles! And i will merge it

**Comment by RyzenDew** [comment]
image
one Error could you make it so hidapi.lib is extracted or it's pulled down not zipped.

**Comment by nitrostemp** [comment]
just tested on 2022, it failed to compile saying that aziaudio.lib was not there, i manually built aziaudio and reran the build and everything built.

**Comment by alex-free** [comment]
Definitely expected at this stage of development… save often and always whenever you accomplish something fr and especially in the game so the same because of the game engine intsslf taking your money !… if you can’t get the tool chain to build you have problems because it easily built itself with gcc 11.2.0…On 4/21/23 at 8:16 PM, nitrostemp wrote:
                
            
            
                
                    From: "nitrostemp" ***@***.***>Date: April 21, 2023To: "blawar/ooot" ***@***.***>Cc: "Subscribed" ***@***.***>Subject: Re: [blawar/ooot] Fix Visual Studio 2022 build (PR #344)
                
                
just tested on 2022, it failed to compile saying that aziaudio.lib was not there, i manually built aziaudio and reran the build and everything built.

**Comment by xoascf** [comment]
> just tested on 2022, it failed to compile saying that aziaudio.lib was not there, i manually built aziaudio and reran the build and everything built.

Hmm, so, all that is needed is to rearrange the build order...

**Comment by RyzenDew** [comment]
RaphnetAdapter should be third in build order if that's possible

**Pull request merged**
