### PR TITLE
Create message_data_pt-PT.h

### PR DESCRIPTION
**Pull request by zurkke55**

### CODE REVIEW

**Comment by blawar** [comment]
Hello, is there a need to add an extra pt in the file name?  I believe the standard is pt for regular Portuguese and pt-BR for Brazilian Portuguese.  Is this correct?

**Comment by zurkke55** [comment]
Hello! I wrote it that way because it's more conventional to appear like that, mainly due to the fact that pt-BR is usually more widespread, so there's no confusion to the devs and eventually the player, but I'm open to any corrections.

**Comment by blawar** [comment]
I see, that is fine.  just add a dash between it and capitalize the country code: message_data_pt-PT.h

**Comment by blawar** [comment]
duplicative of #257

**Pull request closed without merging**
